[AP-2140] add PyGithub on x86 machines
We only use this library in test code so we don't need to add it to all
builder images
We need to pin to a specific version of cryptography, as the latest
isn't compatible with the version of OpenSSL we use:
```
File "/root/miniconda3/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
4006    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
4007AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```