Fix KUBECTL_VERSION=`Timed out while waiting on cache␤`
While working on #955, an unrelated job failed and had to be restarted:
https://gitlab.ddbuild.io/DataDog/datadog-agent-buildimages/-/jobs/1083853287

The error was kind of cryptic:
```
/bin/linux/amd64/kubectl' -Lo /tmp/kubectl
127.6 curl: (3) URL rejected: Malformed input to a URL function
ERROR: process "/bin/sh -c /setup/tools.sh" did not complete successfully: exit code: 3
```
There was no exploitable error in the console output, nor in the
[full log](https://gitlab.ddbuild.io/DataDog/datadog-agent-buildimages/-/jobs/1083853287/viewer).

Fortunately, one could find a suspicious line in the
[raw log](https://gitlab.ddbuild.io/DataDog/datadog-agent-buildimages/-/jobs/1083853287/raw):
```
127.3 + install-binary --version 'Timed out while waiting on cache-iad-kjyo7100113-IAD
' --digest '' --url 'https://dl.k8s.io/release/Timed out while waiting on cache-iad-kjyo7100113-IAD
/bin/linux/amd64/kubectl' --name kubectl
```
💡 `KUBECTL_VERSION` was set to
`Timed out while waiting on cache-iad-kjyo7100113-IAD␤`, because this is
what `curl` printed to the standard output stream in its preceding
invocation.

The present change aims at fixing it by:
- add fail-fast flags to `curl` invocations,
- enable internal retries instead of having to retry the full job.