[python] Pin zlib conda package (#191)
Pins the zlib conda package to zlib=1.2.11=h7b6447c_3, as the latest one (zlib-1.2.11-h7f8727e_4) was likely built with a newer toolchain that makes it fail in our old builders:

ImportError: /lib64/libc.so.6: version GLIBC_2.14 not found (required by /root/miniconda3/envs/ddpy2/lib/python2.7/lib-dynload/../../libz.so.1)