Refresh MSYS2 packages before installing them in the Windows image (#1342)
### Motivation

`main` is
[failing](https://gitlab.ddbuild.io/DataDog/datadog-agent-buildimages/-/pipelines/140122430)
because the MSYS2 step of the Windows image build asks for package
versions that no MSYS2 mirror has anymore.

```
error: failed retrieving file 'mingw-w64-x86_64-headers-git-12.0.0.r423.g8bcd5fc1a-1-any.pkg.tar.zst' from mirror.msys2.org : The requested URL returned error: 404
error: failed to commit transaction (download library error)
ridk install 3 returned 1.
```